from flask import Flask, flash, request, redirect, render_template, session, g
from models import connect_db, db, Users, Team
from forms import UserForm, ChatForm, LoginForm
from methods import create_profile, team, user_profile, get_users_basic_team, get_all_footballers, get_users_personal_info, get_classic_league, sort_by_total_points, organize_by_total_points, organize_by_event_points, organize_by_points_per_game, organize_by_form, organize_by_minutes, organize_by_price
import os

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL','postgresql:///fantasy_am_db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_ECHO'] = True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY','secret1' )


connect_db(app)

# home route ###################################################################
@app.route('/')
def root_route():
    return redirect('/home')


@app.route('/home')
def home_route():
    return render_template('home.html')


# REGISTER AND CREATE NEW USER table and the associated team table ##############
@app.route('/register', methods=['GET', 'POST'])
def register_route():
    # using flask-what-the-forms here
    form = UserForm()

    # grabbing the form data for use in our create_profile method
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        team_id = form.team_id.data

        # use the form data to run the create_profile method.
        # this method hits all the necessary endpoints and creates the user's profile
        create_profile(email, password, team_id)

        # assign the register method to the var new_user -- our user.register method hashes the password
        new_user = Users.register(email, password, team_id)

        # add and commit our new user to our datbase
        db.session.add(new_user)
        db.session.commit()

        # add the new_user to the session byinew_user.id
        session['user_id'] = new_user.id

        # redirect to the next part of creating the team table, and pass along the new user's id to associate it with the new user -- this table will hold all the info about
        # the user's team...like player stats as well as the user's team name plus a bunch more.
        return redirect(f'/user/create/{new_user.id}')

    # if the form hasn't been submitted yet render the register html
    return render_template('/register.html', form=form)


# CREATE A NEW TEAM FOR OUR NEW USER FROM REGISTER
@app.route('/user/create/<int:user_id>')
def create_user(user_id):
    # 1st- create a new team in the Team table and associate it with the new user that was just created
    # through the register route. All the rows in this table ARE nullable so we just need to point this team
    # at the new user first.
    user = Users.query.get_or_404(user_id)
    user.team_instance = 1
    db.session.commit()

    new_team = Team(user_id=user_id)

    db.session.add(new_team)
    db.session.commit()

    # 2nd - grab the new team we created with it's assciation to the user that was just registered and use the response data from the imported file 'user' to create the new user's data
    new_user = Team.query.get_or_404(user_id)

    new_user.team_name = user_profile['team_name']
    new_user.fav_team = user_profile['fav_team']
    new_user.fav_team_id = user_profile['fav_team_id']
    new_user.fav_team_logo = user_profile['fav_team_logo']
    new_user.fav_team_colors = user_profile['fav_team_colors']
    new_user.fav_team_jersey = user_profile['fav_team_jersey']
    new_user.fav_team_jersey_goal = user_profile['fav_team_jersey_goal']
    new_user.classic_league_id = user_profile['classic_league_id']
    new_user.overall_points = user_profile['overall_points']
    new_user.gameweek_points = user_profile['gameweek_points']
    new_user.classic_league_name = user_profile['classic_league_name']
    new_user.classic_league_rank = user_profile['classic_league_rank']
    new_user.classic_league_rank_previous = user_profile['classic_league_rank_previous']

    # player 1
    new_user.p1_chance_of_playing_next_round = user_profile['p1_chance_of_playing_next_round']
    new_user.p1_chance_of_playing_this_round = user_profile['p1_chance_of_playing_this_round']
    new_user.p1_cost_change_event = user_profile['p1_cost_change_event']
    new_user.p1_cost_change_event_fall = user_profile['p1_cost_change_event_fall']
    new_user.p1_cost_change_start = user_profile['p1_cost_change_start']
    new_user.p1_cost_change_start_fall = user_profile['p1_cost_change_start_fall']
    new_user.p1_dreamteam_count = user_profile['p1_dreamteam_count']
    new_user.p1_element_type = user_profile['p1_element_type']
    new_user.p1_event_points = user_profile['p1_event_points']
    new_user.p1_first_name = user_profile['p1_first_name']
    new_user.p1_form = user_profile['p1_form']
    new_user.p1_player_id = user_profile['p1_player_id']
    new_user.p1_in_dreamteam = user_profile['p1_in_dreamteam']
    new_user.p1_now_cost = user_profile['p1_now_cost']
    new_user.p1_photo = user_profile['p1_photo']
    new_user.p1_points_per_game = user_profile['p1_points_per_game']
    new_user.p1_second_name = user_profile['p1_second_name']
    new_user.p1_selected_by_percent = user_profile['p1_selected_by_percent']
    new_user.p1_special = user_profile['p1_special']
    new_user.p1_squad_number = user_profile['p1_squad_number']
    new_user.p1_status = user_profile['p1_status']
    new_user.p1_team = user_profile['p1_team']
    new_user.p1_team_code = user_profile['p1_team_code']
    new_user.p1_total_points = user_profile['p1_total_points']
    new_user.p1_value_form = user_profile['p1_value_form']
    new_user.p1_value_season = user_profile['p1_value_season']
    new_user.p1_web_name = user_profile['p1_web_name']
    new_user.p1_minutes = user_profile['p1_minutes']
    new_user.p1_goals_scored = user_profile['p1_goals_scored']
    new_user.p1_assists = user_profile['p1_assists']
    new_user.p1_clean_sheets = user_profile['p1_clean_sheets']
    new_user.p1_own_goals = user_profile['p1_own_goals']
    new_user.p1_penalties_saved = user_profile['p1_penalties_saved']
    new_user.p1_penalties_missed = user_profile['p1_penalties_missed']
    new_user.p1_goals_conceded = user_profile['p1_goals_conceded']
    new_user.p1_yellow_cards = user_profile['p1_yellow_cards']
    new_user.p1_red_cards = user_profile['p1_red_cards']
    new_user.p1_saves = user_profile['p1_saves']
    new_user.p1_bonus = user_profile['p1_bonus']
    new_user.p1_bps = user_profile['p1_bps']
    new_user.p1_team_jersey = user_profile['p1_team_jersey']
    new_user.p1_team_logo = user_profile['p1_team_logo']
    new_user.p1_team_colors = user_profile['p1_team_colors']
    new_user.p1_team_name = user_profile['p1_team_name']

    # player 2
    new_user.p2_chance_of_playing_next_round = user_profile['p2_chance_of_playing_next_round']
    new_user.p2_chance_of_playing_this_round = user_profile['p2_chance_of_playing_this_round']
    new_user.p2_cost_change_event = user_profile['p2_cost_change_event']
    new_user.p2_cost_change_event_fall = user_profile['p2_cost_change_event_fall']
    new_user.p2_cost_change_start = user_profile['p2_cost_change_start']
    new_user.p2_cost_change_start_fall = user_profile['p2_cost_change_start_fall']
    new_user.p2_dreamteam_count = user_profile['p2_dreamteam_count']
    new_user.p2_element_type = user_profile['p2_element_type']
    new_user.p2_event_points = user_profile['p2_event_points']
    new_user.p2_first_name = user_profile['p2_first_name']
    new_user.p2_form = user_profile['p2_form']
    new_user.p2_player_id = user_profile['p2_player_id']
    new_user.p2_in_dreamteam = user_profile['p2_in_dreamteam']
    new_user.p2_now_cost = user_profile['p2_now_cost']
    new_user.p2_photo = user_profile['p2_photo']
    new_user.p2_points_per_game = user_profile['p2_points_per_game']
    new_user.p2_second_name = user_profile['p2_second_name']
    new_user.p2_selected_by_percent = user_profile['p2_selected_by_percent']
    new_user.p2_special = user_profile['p2_special']
    new_user.p2_squad_number = user_profile['p2_squad_number']
    new_user.p2_status = user_profile['p2_status']
    new_user.p2_team = user_profile['p2_team']
    new_user.p2_team_code = user_profile['p2_team_code']
    new_user.p2_total_points = user_profile['p2_total_points']
    new_user.p2_value_form = user_profile['p2_value_form']
    new_user.p2_value_season = user_profile['p2_value_season']
    new_user.p2_web_name = user_profile['p2_web_name']
    new_user.p2_minutes = user_profile['p2_minutes']
    new_user.p2_goals_scored = user_profile['p2_goals_scored']
    new_user.p2_assists = user_profile['p2_assists']
    new_user.p2_clean_sheets = user_profile['p2_clean_sheets']
    new_user.p2_own_goals = user_profile['p2_own_goals']
    new_user.p2_penalties_saved = user_profile['p2_penalties_saved']
    new_user.p2_penalties_missed = user_profile['p2_penalties_missed']
    new_user.p2_goals_conceded = user_profile['p2_goals_conceded']
    new_user.p2_yellow_cards = user_profile['p2_yellow_cards']
    new_user.p2_red_cards = user_profile['p2_red_cards']
    new_user.p2_saves = user_profile['p2_saves']
    new_user.p2_bonus = user_profile['p2_bonus']
    new_user.p2_bps = user_profile['p2_bps']
    new_user.p2_team_jersey = user_profile['p2_team_jersey']
    new_user.p2_team_logo = user_profile['p2_team_logo']
    new_user.p2_team_colors = user_profile['p2_team_colors']
    new_user.p2_team_name = user_profile['p2_team_name']

    # player 3
    new_user.p3_chance_of_playing_next_round = user_profile['p3_chance_of_playing_next_round']
    new_user.p3_chance_of_playing_this_round = user_profile['p3_chance_of_playing_this_round']
    new_user.p3_cost_change_event = user_profile['p3_cost_change_event']
    new_user.p3_cost_change_event_fall = user_profile['p3_cost_change_event_fall']
    new_user.p3_cost_change_start = user_profile['p3_cost_change_start']
    new_user.p3_cost_change_start_fall = user_profile['p3_cost_change_start_fall']
    new_user.p3_dreamteam_count = user_profile['p3_dreamteam_count']
    new_user.p3_element_type = user_profile['p3_element_type']
    new_user.p3_event_points = user_profile['p3_event_points']
    new_user.p3_first_name = user_profile['p3_first_name']
    new_user.p3_form = user_profile['p3_form']
    new_user.p3_player_id = user_profile['p3_player_id']
    new_user.p3_in_dreamteam = user_profile['p3_in_dreamteam']
    new_user.p3_now_cost = user_profile['p3_now_cost']
    new_user.p3_photo = user_profile['p3_photo']
    new_user.p3_points_per_game = user_profile['p3_points_per_game']
    new_user.p3_second_name = user_profile['p3_second_name']
    new_user.p3_selected_by_percent = user_profile['p3_selected_by_percent']
    new_user.p3_special = user_profile['p3_special']
    new_user.p3_squad_number = user_profile['p3_squad_number']
    new_user.p3_status = user_profile['p3_status']
    new_user.p3_team = user_profile['p3_team']
    new_user.p3_team_code = user_profile['p3_team_code']
    new_user.p3_total_points = user_profile['p3_total_points']
    new_user.p3_value_form = user_profile['p3_value_form']
    new_user.p3_value_season = user_profile['p3_value_season']
    new_user.p3_web_name = user_profile['p3_web_name']
    new_user.p3_minutes = user_profile['p3_minutes']
    new_user.p3_goals_scored = user_profile['p3_goals_scored']
    new_user.p3_assists = user_profile['p3_assists']
    new_user.p3_clean_sheets = user_profile['p3_clean_sheets']
    new_user.p3_own_goals = user_profile['p3_own_goals']
    new_user.p3_penalties_saved = user_profile['p3_penalties_saved']
    new_user.p3_penalties_missed = user_profile['p3_penalties_missed']
    new_user.p3_goals_conceded = user_profile['p3_goals_conceded']
    new_user.p3_yellow_cards = user_profile['p3_yellow_cards']
    new_user.p3_red_cards = user_profile['p3_red_cards']
    new_user.p3_saves = user_profile['p3_saves']
    new_user.p3_bonus = user_profile['p3_bonus']
    new_user.p3_bps = user_profile['p3_bps']
    new_user.p3_team_jersey = user_profile['p3_team_jersey']
    new_user.p3_team_logo = user_profile['p3_team_logo']
    new_user.p3_team_colors = user_profile['p3_team_colors']
    new_user.p3_team_name = user_profile['p3_team_name']

    # player 4
    new_user.p4_chance_of_playing_next_round = user_profile['p4_chance_of_playing_next_round']
    new_user.p4_chance_of_playing_this_round = user_profile['p4_chance_of_playing_this_round']
    new_user.p4_cost_change_event = user_profile['p4_cost_change_event']
    new_user.p4_cost_change_event_fall = user_profile['p4_cost_change_event_fall']
    new_user.p4_cost_change_start = user_profile['p4_cost_change_start']
    new_user.p4_cost_change_start_fall = user_profile['p4_cost_change_start_fall']
    new_user.p4_dreamteam_count = user_profile['p4_dreamteam_count']
    new_user.p4_element_type = user_profile['p4_element_type']
    new_user.p4_event_points = user_profile['p4_event_points']
    new_user.p4_first_name = user_profile['p4_first_name']
    new_user.p4_form = user_profile['p4_form']
    new_user.p4_player_id = user_profile['p4_player_id']
    new_user.p4_in_dreamteam = user_profile['p4_in_dreamteam']
    new_user.p4_now_cost = user_profile['p4_now_cost']
    new_user.p4_photo = user_profile['p4_photo']
    new_user.p4_points_per_game = user_profile['p4_points_per_game']
    new_user.p4_second_name = user_profile['p4_second_name']
    new_user.p4_selected_by_percent = user_profile['p4_selected_by_percent']
    new_user.p4_special = user_profile['p4_special']
    new_user.p4_squad_number = user_profile['p4_squad_number']
    new_user.p4_status = user_profile['p4_status']
    new_user.p4_team = user_profile['p4_team']
    new_user.p4_team_code = user_profile['p4_team_code']
    new_user.p4_total_points = user_profile['p4_total_points']
    new_user.p4_value_form = user_profile['p4_value_form']
    new_user.p4_value_season = user_profile['p4_value_season']
    new_user.p4_web_name = user_profile['p4_web_name']
    new_user.p4_minutes = user_profile['p4_minutes']
    new_user.p4_goals_scored = user_profile['p4_goals_scored']
    new_user.p4_assists = user_profile['p4_assists']
    new_user.p4_clean_sheets = user_profile['p4_clean_sheets']
    new_user.p4_own_goals = user_profile['p4_own_goals']
    new_user.p4_penalties_saved = user_profile['p4_penalties_saved']
    new_user.p4_penalties_missed = user_profile['p4_penalties_missed']
    new_user.p4_goals_conceded = user_profile['p4_goals_conceded']
    new_user.p4_yellow_cards = user_profile['p4_yellow_cards']
    new_user.p4_red_cards = user_profile['p4_red_cards']
    new_user.p4_saves = user_profile['p4_saves']
    new_user.p4_bonus = user_profile['p4_bonus']
    new_user.p4_bps = user_profile['p4_bps']
    new_user.p4_team_jersey = user_profile['p4_team_jersey']
    new_user.p4_team_logo = user_profile['p4_team_logo']
    new_user.p4_team_colors = user_profile['p4_team_colors']
    new_user.p4_team_name = user_profile['p4_team_name']

    # player 5
    new_user.p5_chance_of_playing_next_round = user_profile['p5_chance_of_playing_next_round']
    new_user.p5_chance_of_playing_this_round = user_profile['p5_chance_of_playing_this_round']
    new_user.p5_cost_change_event = user_profile['p5_cost_change_event']
    new_user.p5_cost_change_event_fall = user_profile['p5_cost_change_event_fall']
    new_user.p5_cost_change_start = user_profile['p5_cost_change_start']
    new_user.p5_cost_change_start_fall = user_profile['p5_cost_change_start_fall']
    new_user.p5_dreamteam_count = user_profile['p5_dreamteam_count']
    new_user.p5_element_type = user_profile['p5_element_type']
    new_user.p5_event_points = user_profile['p5_event_points']
    new_user.p5_first_name = user_profile['p5_first_name']
    new_user.p5_form = user_profile['p5_form']
    new_user.p5_player_id = user_profile['p5_player_id']
    new_user.p5_in_dreamteam = user_profile['p5_in_dreamteam']
    new_user.p5_now_cost = user_profile['p5_now_cost']
    new_user.p5_photo = user_profile['p5_photo']
    new_user.p5_points_per_game = user_profile['p5_points_per_game']
    new_user.p5_second_name = user_profile['p5_second_name']
    new_user.p5_selected_by_percent = user_profile['p5_selected_by_percent']
    new_user.p5_special = user_profile['p5_special']
    new_user.p5_squad_number = user_profile['p5_squad_number']
    new_user.p5_status = user_profile['p5_status']
    new_user.p5_team = user_profile['p5_team']
    new_user.p5_team_code = user_profile['p5_team_code']
    new_user.p5_total_points = user_profile['p5_total_points']
    new_user.p5_value_form = user_profile['p5_value_form']
    new_user.p5_value_season = user_profile['p5_value_season']
    new_user.p5_web_name = user_profile['p5_web_name']
    new_user.p5_minutes = user_profile['p5_minutes']
    new_user.p5_goals_scored = user_profile['p5_goals_scored']
    new_user.p5_assists = user_profile['p5_assists']
    new_user.p5_clean_sheets = user_profile['p5_clean_sheets']
    new_user.p5_own_goals = user_profile['p5_own_goals']
    new_user.p5_penalties_saved = user_profile['p5_penalties_saved']
    new_user.p5_penalties_missed = user_profile['p5_penalties_missed']
    new_user.p5_goals_conceded = user_profile['p5_goals_conceded']
    new_user.p5_yellow_cards = user_profile['p5_yellow_cards']
    new_user.p5_red_cards = user_profile['p5_red_cards']
    new_user.p5_saves = user_profile['p5_saves']
    new_user.p5_bonus = user_profile['p5_bonus']
    new_user.p5_bps = user_profile['p5_bps']
    new_user.p5_team_jersey = user_profile['p5_team_jersey']
    new_user.p5_team_logo = user_profile['p5_team_logo']
    new_user.p5_team_colors = user_profile['p5_team_colors']
    new_user.p5_team_name = user_profile['p5_team_name']

    # player 6
    new_user.p6_chance_of_playing_next_round = user_profile['p6_chance_of_playing_next_round']
    new_user.p6_chance_of_playing_this_round = user_profile['p6_chance_of_playing_this_round']
    new_user.p6_cost_change_event = user_profile['p6_cost_change_event']
    new_user.p6_cost_change_event_fall = user_profile['p6_cost_change_event_fall']
    new_user.p6_cost_change_start = user_profile['p6_cost_change_start']
    new_user.p6_cost_change_start_fall = user_profile['p6_cost_change_start_fall']
    new_user.p6_dreamteam_count = user_profile['p6_dreamteam_count']
    new_user.p6_element_type = user_profile['p6_element_type']
    new_user.p6_event_points = user_profile['p6_event_points']
    new_user.p6_first_name = user_profile['p6_first_name']
    new_user.p6_form = user_profile['p6_form']
    new_user.p6_player_id = user_profile['p6_player_id']
    new_user.p6_in_dreamteam = user_profile['p6_in_dreamteam']
    new_user.p6_now_cost = user_profile['p6_now_cost']
    new_user.p6_photo = user_profile['p6_photo']
    new_user.p6_points_per_game = user_profile['p6_points_per_game']
    new_user.p6_second_name = user_profile['p6_second_name']
    new_user.p6_selected_by_percent = user_profile['p6_selected_by_percent']
    new_user.p6_special = user_profile['p6_special']
    new_user.p6_squad_number = user_profile['p6_squad_number']
    new_user.p6_status = user_profile['p6_status']
    new_user.p6_team = user_profile['p6_team']
    new_user.p6_team_code = user_profile['p6_team_code']
    new_user.p6_total_points = user_profile['p6_total_points']
    new_user.p6_value_form = user_profile['p6_value_form']
    new_user.p6_value_season = user_profile['p6_value_season']
    new_user.p6_web_name = user_profile['p6_web_name']
    new_user.p6_minutes = user_profile['p6_minutes']
    new_user.p6_goals_scored = user_profile['p6_goals_scored']
    new_user.p6_assists = user_profile['p6_assists']
    new_user.p6_clean_sheets = user_profile['p6_clean_sheets']
    new_user.p6_own_goals = user_profile['p6_own_goals']
    new_user.p6_penalties_saved = user_profile['p6_penalties_saved']
    new_user.p6_penalties_missed = user_profile['p6_penalties_missed']
    new_user.p6_goals_conceded = user_profile['p6_goals_conceded']
    new_user.p6_yellow_cards = user_profile['p6_yellow_cards']
    new_user.p6_red_cards = user_profile['p6_red_cards']
    new_user.p6_saves = user_profile['p6_saves']
    new_user.p6_bonus = user_profile['p6_bonus']
    new_user.p6_bps = user_profile['p6_bps']
    new_user.p6_team_jersey = user_profile['p6_team_jersey']
    new_user.p6_team_logo = user_profile['p6_team_logo']
    new_user.p6_team_colors = user_profile['p6_team_colors']
    new_user.p6_team_name = user_profile['p6_team_name']

    # player 7
    new_user.p7_chance_of_playing_next_round = user_profile['p7_chance_of_playing_next_round']
    new_user.p7_chance_of_playing_this_round = user_profile['p7_chance_of_playing_this_round']
    new_user.p7_cost_change_event = user_profile['p7_cost_change_event']
    new_user.p7_cost_change_event_fall = user_profile['p7_cost_change_event_fall']
    new_user.p7_cost_change_start = user_profile['p7_cost_change_start']
    new_user.p7_cost_change_start_fall = user_profile['p7_cost_change_start_fall']
    new_user.p7_dreamteam_count = user_profile['p7_dreamteam_count']
    new_user.p7_element_type = user_profile['p7_element_type']
    new_user.p7_event_points = user_profile['p7_event_points']
    new_user.p7_first_name = user_profile['p7_first_name']
    new_user.p7_form = user_profile['p7_form']
    new_user.p7_player_id = user_profile['p7_player_id']
    new_user.p7_in_dreamteam = user_profile['p7_in_dreamteam']
    new_user.p7_now_cost = user_profile['p7_now_cost']
    new_user.p7_photo = user_profile['p7_photo']
    new_user.p7_points_per_game = user_profile['p7_points_per_game']
    new_user.p7_second_name = user_profile['p7_second_name']
    new_user.p7_selected_by_percent = user_profile['p7_selected_by_percent']
    new_user.p7_special = user_profile['p7_special']
    new_user.p7_squad_number = user_profile['p7_squad_number']
    new_user.p7_status = user_profile['p7_status']
    new_user.p7_team = user_profile['p7_team']
    new_user.p7_team_code = user_profile['p7_team_code']
    new_user.p7_total_points = user_profile['p7_total_points']
    new_user.p7_value_form = user_profile['p7_value_form']
    new_user.p7_value_season = user_profile['p7_value_season']
    new_user.p7_web_name = user_profile['p7_web_name']
    new_user.p7_minutes = user_profile['p7_minutes']
    new_user.p7_goals_scored = user_profile['p7_goals_scored']
    new_user.p7_assists = user_profile['p7_assists']
    new_user.p7_clean_sheets = user_profile['p7_clean_sheets']
    new_user.p7_own_goals = user_profile['p7_own_goals']
    new_user.p7_penalties_saved = user_profile['p7_penalties_saved']
    new_user.p7_penalties_missed = user_profile['p7_penalties_missed']
    new_user.p7_goals_conceded = user_profile['p7_goals_conceded']
    new_user.p7_yellow_cards = user_profile['p7_yellow_cards']
    new_user.p7_red_cards = user_profile['p7_red_cards']
    new_user.p7_saves = user_profile['p7_saves']
    new_user.p7_bonus = user_profile['p7_bonus']
    new_user.p7_bps = user_profile['p7_bps']
    new_user.p7_team_jersey = user_profile['p7_team_jersey']
    new_user.p7_team_logo = user_profile['p7_team_logo']
    new_user.p7_team_colors = user_profile['p7_team_colors']
    new_user.p7_team_name = user_profile['p7_team_name']

    # player 8
    new_user.p8_chance_of_playing_next_round = user_profile['p8_chance_of_playing_next_round']
    new_user.p8_chance_of_playing_this_round = user_profile['p8_chance_of_playing_this_round']
    new_user.p8_cost_change_event = user_profile['p8_cost_change_event']
    new_user.p8_cost_change_event_fall = user_profile['p8_cost_change_event_fall']
    new_user.p8_cost_change_start = user_profile['p8_cost_change_start']
    new_user.p8_cost_change_start_fall = user_profile['p8_cost_change_start_fall']
    new_user.p8_dreamteam_count = user_profile['p8_dreamteam_count']
    new_user.p8_element_type = user_profile['p8_element_type']
    new_user.p8_event_points = user_profile['p8_event_points']
    new_user.p8_first_name = user_profile['p8_first_name']
    new_user.p8_form = user_profile['p8_form']
    new_user.p8_player_id = user_profile['p8_player_id']
    new_user.p8_in_dreamteam = user_profile['p8_in_dreamteam']
    new_user.p8_now_cost = user_profile['p8_now_cost']
    new_user.p8_photo = user_profile['p8_photo']
    new_user.p8_points_per_game = user_profile['p8_points_per_game']
    new_user.p8_second_name = user_profile['p8_second_name']
    new_user.p8_selected_by_percent = user_profile['p8_selected_by_percent']
    new_user.p8_special = user_profile['p8_special']
    new_user.p8_squad_number = user_profile['p8_squad_number']
    new_user.p8_status = user_profile['p8_status']
    new_user.p8_team = user_profile['p8_team']
    new_user.p8_team_code = user_profile['p8_team_code']
    new_user.p8_total_points = user_profile['p8_total_points']
    new_user.p8_value_form = user_profile['p8_value_form']
    new_user.p8_value_season = user_profile['p8_value_season']
    new_user.p8_web_name = user_profile['p8_web_name']
    new_user.p8_minutes = user_profile['p8_minutes']
    new_user.p8_goals_scored = user_profile['p8_goals_scored']
    new_user.p8_assists = user_profile['p8_assists']
    new_user.p8_clean_sheets = user_profile['p8_clean_sheets']
    new_user.p8_own_goals = user_profile['p8_own_goals']
    new_user.p8_penalties_saved = user_profile['p8_penalties_saved']
    new_user.p8_penalties_missed = user_profile['p8_penalties_missed']
    new_user.p8_goals_conceded = user_profile['p8_goals_conceded']
    new_user.p8_yellow_cards = user_profile['p8_yellow_cards']
    new_user.p8_red_cards = user_profile['p8_red_cards']
    new_user.p8_saves = user_profile['p8_saves']
    new_user.p8_bonus = user_profile['p8_bonus']
    new_user.p8_bps = user_profile['p8_bps']
    new_user.p8_team_jersey = user_profile['p8_team_jersey']
    new_user.p8_team_logo = user_profile['p8_team_logo']
    new_user.p8_team_colors = user_profile['p8_team_colors']
    new_user.p8_team_name = user_profile['p8_team_name']

    # player 9
    new_user.p9_chance_of_playing_next_round = user_profile['p9_chance_of_playing_next_round']
    new_user.p9_chance_of_playing_this_round = user_profile['p9_chance_of_playing_this_round']
    new_user.p9_cost_change_event = user_profile['p9_cost_change_event']
    new_user.p9_cost_change_event_fall = user_profile['p9_cost_change_event_fall']
    new_user.p9_cost_change_start = user_profile['p9_cost_change_start']
    new_user.p9_cost_change_start_fall = user_profile['p9_cost_change_start_fall']
    new_user.p9_dreamteam_count = user_profile['p9_dreamteam_count']
    new_user.p9_element_type = user_profile['p9_element_type']
    new_user.p9_event_points = user_profile['p9_event_points']
    new_user.p9_first_name = user_profile['p9_first_name']
    new_user.p9_form = user_profile['p9_form']
    new_user.p9_player_id = user_profile['p9_player_id']
    new_user.p9_in_dreamteam = user_profile['p9_in_dreamteam']
    new_user.p9_now_cost = user_profile['p9_now_cost']
    new_user.p9_photo = user_profile['p9_photo']
    new_user.p9_points_per_game = user_profile['p9_points_per_game']
    new_user.p9_second_name = user_profile['p9_second_name']
    new_user.p9_selected_by_percent = user_profile['p9_selected_by_percent']
    new_user.p9_special = user_profile['p9_special']
    new_user.p9_squad_number = user_profile['p9_squad_number']
    new_user.p9_status = user_profile['p9_status']
    new_user.p9_team = user_profile['p9_team']
    new_user.p9_team_code = user_profile['p9_team_code']
    new_user.p9_total_points = user_profile['p9_total_points']
    new_user.p9_value_form = user_profile['p9_value_form']
    new_user.p9_value_season = user_profile['p9_value_season']
    new_user.p9_web_name = user_profile['p9_web_name']
    new_user.p9_minutes = user_profile['p9_minutes']
    new_user.p9_goals_scored = user_profile['p9_goals_scored']
    new_user.p9_assists = user_profile['p9_assists']
    new_user.p9_clean_sheets = user_profile['p9_clean_sheets']
    new_user.p9_own_goals = user_profile['p9_own_goals']
    new_user.p9_penalties_saved = user_profile['p9_penalties_saved']
    new_user.p9_penalties_missed = user_profile['p9_penalties_missed']
    new_user.p9_goals_conceded = user_profile['p9_goals_conceded']
    new_user.p9_yellow_cards = user_profile['p9_yellow_cards']
    new_user.p9_red_cards = user_profile['p9_red_cards']
    new_user.p9_saves = user_profile['p9_saves']
    new_user.p9_bonus = user_profile['p9_bonus']
    new_user.p9_bps = user_profile['p9_bps']
    new_user.p9_team_jersey = user_profile['p9_team_jersey']
    new_user.p9_team_logo = user_profile['p9_team_logo']
    new_user.p9_team_colors = user_profile['p9_team_colors']
    new_user.p9_team_name = user_profile['p9_team_name']

    # player 10
    new_user.p10_chance_of_playing_next_round = user_profile['p10_chance_of_playing_next_round']
    new_user.p10_chance_of_playing_this_round = user_profile['p10_chance_of_playing_this_round']
    new_user.p10_cost_change_event = user_profile['p10_cost_change_event']
    new_user.p10_cost_change_event_fall = user_profile['p10_cost_change_event_fall']
    new_user.p10_cost_change_start = user_profile['p10_cost_change_start']
    new_user.p10_cost_change_start_fall = user_profile['p10_cost_change_start_fall']
    new_user.p10_dreamteam_count = user_profile['p10_dreamteam_count']
    new_user.p10_element_type = user_profile['p10_element_type']
    new_user.p10_event_points = user_profile['p10_event_points']
    new_user.p10_first_name = user_profile['p10_first_name']
    new_user.p10_form = user_profile['p10_form']
    new_user.p10_player_id = user_profile['p10_player_id']
    new_user.p10_in_dreamteam = user_profile['p10_in_dreamteam']
    new_user.p10_now_cost = user_profile['p10_now_cost']
    new_user.p10_photo = user_profile['p10_photo']
    new_user.p10_points_per_game = user_profile['p10_points_per_game']
    new_user.p10_second_name = user_profile['p10_second_name']
    new_user.p10_selected_by_percent = user_profile['p10_selected_by_percent']
    new_user.p10_special = user_profile['p10_special']
    new_user.p10_squad_number = user_profile['p10_squad_number']
    new_user.p10_status = user_profile['p10_status']
    new_user.p10_team = user_profile['p10_team']
    new_user.p10_team_code = user_profile['p10_team_code']
    new_user.p10_total_points = user_profile['p10_total_points']
    new_user.p10_value_form = user_profile['p10_value_form']
    new_user.p10_value_season = user_profile['p10_value_season']
    new_user.p10_web_name = user_profile['p10_web_name']
    new_user.p10_minutes = user_profile['p10_minutes']
    new_user.p10_goals_scored = user_profile['p10_goals_scored']
    new_user.p10_assists = user_profile['p10_assists']
    new_user.p10_clean_sheets = user_profile['p10_clean_sheets']
    new_user.p10_own_goals = user_profile['p10_own_goals']
    new_user.p10_penalties_saved = user_profile['p10_penalties_saved']
    new_user.p10_penalties_missed = user_profile['p10_penalties_missed']
    new_user.p10_goals_conceded = user_profile['p10_goals_conceded']
    new_user.p10_yellow_cards = user_profile['p10_yellow_cards']
    new_user.p10_red_cards = user_profile['p10_red_cards']
    new_user.p10_saves = user_profile['p10_saves']
    new_user.p10_bonus = user_profile['p10_bonus']
    new_user.p10_bps = user_profile['p10_bps']
    new_user.p10_team_jersey = user_profile['p10_team_jersey']
    new_user.p10_team_logo = user_profile['p10_team_logo']
    new_user.p10_team_colors = user_profile['p10_team_colors']
    new_user.p10_team_name = user_profile['p10_team_name']

    # player 11
    new_user.p11_chance_of_playing_next_round = user_profile['p11_chance_of_playing_next_round']
    new_user.p11_chance_of_playing_this_round = user_profile['p11_chance_of_playing_this_round']
    new_user.p11_cost_change_event = user_profile['p11_cost_change_event']
    new_user.p11_cost_change_event_fall = user_profile['p11_cost_change_event_fall']
    new_user.p11_cost_change_start = user_profile['p11_cost_change_start']
    new_user.p11_cost_change_start_fall = user_profile['p11_cost_change_start_fall']
    new_user.p11_dreamteam_count = user_profile['p11_dreamteam_count']
    new_user.p11_element_type = user_profile['p11_element_type']
    new_user.p11_event_points = user_profile['p11_event_points']
    new_user.p11_first_name = user_profile['p11_first_name']
    new_user.p11_form = user_profile['p11_form']
    new_user.p11_player_id = user_profile['p11_player_id']
    new_user.p11_in_dreamteam = user_profile['p11_in_dreamteam']
    new_user.p11_now_cost = user_profile['p11_now_cost']
    new_user.p11_photo = user_profile['p11_photo']
    new_user.p11_points_per_game = user_profile['p11_points_per_game']
    new_user.p11_second_name = user_profile['p11_second_name']
    new_user.p11_selected_by_percent = user_profile['p11_selected_by_percent']
    new_user.p11_special = user_profile['p11_special']
    new_user.p11_squad_number = user_profile['p11_squad_number']
    new_user.p11_status = user_profile['p11_status']
    new_user.p11_team = user_profile['p11_team']
    new_user.p11_team_code = user_profile['p11_team_code']
    new_user.p11_total_points = user_profile['p11_total_points']
    new_user.p11_value_form = user_profile['p11_value_form']
    new_user.p11_value_season = user_profile['p11_value_season']
    new_user.p11_web_name = user_profile['p11_web_name']
    new_user.p11_minutes = user_profile['p11_minutes']
    new_user.p11_goals_scored = user_profile['p11_goals_scored']
    new_user.p11_assists = user_profile['p11_assists']
    new_user.p11_clean_sheets = user_profile['p11_clean_sheets']
    new_user.p11_own_goals = user_profile['p11_own_goals']
    new_user.p11_penalties_saved = user_profile['p11_penalties_saved']
    new_user.p11_penalties_missed = user_profile['p11_penalties_missed']
    new_user.p11_goals_conceded = user_profile['p11_goals_conceded']
    new_user.p11_yellow_cards = user_profile['p11_yellow_cards']
    new_user.p11_red_cards = user_profile['p11_red_cards']
    new_user.p11_saves = user_profile['p11_saves']
    new_user.p11_bonus = user_profile['p11_bonus']
    new_user.p11_bps = user_profile['p11_bps']
    new_user.p11_team_jersey = user_profile['p11_team_jersey']
    new_user.p11_team_logo = user_profile['p11_team_logo']
    new_user.p11_team_colors = user_profile['p11_team_colors']
    new_user.p11_team_name = user_profile['p11_team_name']

    # player 12
    new_user.p12_chance_of_playing_next_round = user_profile['p12_chance_of_playing_next_round']
    new_user.p12_chance_of_playing_this_round = user_profile['p12_chance_of_playing_this_round']
    new_user.p12_cost_change_event = user_profile['p12_cost_change_event']
    new_user.p12_cost_change_event_fall = user_profile['p12_cost_change_event_fall']
    new_user.p12_cost_change_start = user_profile['p12_cost_change_start']
    new_user.p12_cost_change_start_fall = user_profile['p12_cost_change_start_fall']
    new_user.p12_dreamteam_count = user_profile['p12_dreamteam_count']
    new_user.p12_element_type = user_profile['p12_element_type']
    new_user.p12_event_points = user_profile['p12_event_points']
    new_user.p12_first_name = user_profile['p12_first_name']
    new_user.p12_form = user_profile['p12_form']
    new_user.p12_player_id = user_profile['p12_player_id']
    new_user.p12_in_dreamteam = user_profile['p12_in_dreamteam']
    new_user.p12_now_cost = user_profile['p12_now_cost']
    new_user.p12_photo = user_profile['p12_photo']
    new_user.p12_points_per_game = user_profile['p12_points_per_game']
    new_user.p12_second_name = user_profile['p12_second_name']
    new_user.p12_selected_by_percent = user_profile['p12_selected_by_percent']
    new_user.p12_special = user_profile['p12_special']
    new_user.p12_squad_number = user_profile['p12_squad_number']
    new_user.p12_status = user_profile['p12_status']
    new_user.p12_team = user_profile['p12_team']
    new_user.p12_team_code = user_profile['p12_team_code']
    new_user.p12_total_points = user_profile['p12_total_points']
    new_user.p12_value_form = user_profile['p12_value_form']
    new_user.p12_value_season = user_profile['p12_value_season']
    new_user.p12_web_name = user_profile['p12_web_name']
    new_user.p12_minutes = user_profile['p12_minutes']
    new_user.p12_goals_scored = user_profile['p12_goals_scored']
    new_user.p12_assists = user_profile['p12_assists']
    new_user.p12_clean_sheets = user_profile['p12_clean_sheets']
    new_user.p12_own_goals = user_profile['p12_own_goals']
    new_user.p12_penalties_saved = user_profile['p12_penalties_saved']
    new_user.p12_penalties_missed = user_profile['p12_penalties_missed']
    new_user.p12_goals_conceded = user_profile['p12_goals_conceded']
    new_user.p12_yellow_cards = user_profile['p12_yellow_cards']
    new_user.p12_red_cards = user_profile['p12_red_cards']
    new_user.p12_saves = user_profile['p12_saves']
    new_user.p12_bonus = user_profile['p12_bonus']
    new_user.p12_bps = user_profile['p12_bps']
    new_user.p12_team_jersey = user_profile['p12_team_jersey']
    new_user.p12_team_logo = user_profile['p12_team_logo']
    new_user.p12_team_colors = user_profile['p12_team_colors']
    new_user.p12_team_name = user_profile['p12_team_name']

    # player 13
    new_user.p13_chance_of_playing_next_round = user_profile['p13_chance_of_playing_next_round']
    new_user.p13_chance_of_playing_this_round = user_profile['p13_chance_of_playing_this_round']
    new_user.p13_cost_change_event = user_profile['p13_cost_change_event']
    new_user.p13_cost_change_event_fall = user_profile['p13_cost_change_event_fall']
    new_user.p13_cost_change_start = user_profile['p13_cost_change_start']
    new_user.p13_cost_change_start_fall = user_profile['p13_cost_change_start_fall']
    new_user.p13_dreamteam_count = user_profile['p13_dreamteam_count']
    new_user.p13_element_type = user_profile['p13_element_type']
    new_user.p13_event_points = user_profile['p13_event_points']
    new_user.p13_first_name = user_profile['p13_first_name']
    new_user.p13_form = user_profile['p13_form']
    new_user.p13_player_id = user_profile['p13_player_id']
    new_user.p13_in_dreamteam = user_profile['p13_in_dreamteam']
    new_user.p13_now_cost = user_profile['p13_now_cost']
    new_user.p13_photo = user_profile['p13_photo']
    new_user.p13_points_per_game = user_profile['p13_points_per_game']
    new_user.p13_second_name = user_profile['p13_second_name']
    new_user.p13_selected_by_percent = user_profile['p13_selected_by_percent']
    new_user.p13_special = user_profile['p13_special']
    new_user.p13_squad_number = user_profile['p13_squad_number']
    new_user.p13_status = user_profile['p13_status']
    new_user.p13_team = user_profile['p13_team']
    new_user.p13_team_code = user_profile['p13_team_code']
    new_user.p13_total_points = user_profile['p13_total_points']
    new_user.p13_value_form = user_profile['p13_value_form']
    new_user.p13_value_season = user_profile['p13_value_season']
    new_user.p13_web_name = user_profile['p13_web_name']
    new_user.p13_minutes = user_profile['p13_minutes']
    new_user.p13_goals_scored = user_profile['p13_goals_scored']
    new_user.p13_assists = user_profile['p13_assists']
    new_user.p13_clean_sheets = user_profile['p13_clean_sheets']
    new_user.p13_own_goals = user_profile['p13_own_goals']
    new_user.p13_penalties_saved = user_profile['p13_penalties_saved']
    new_user.p13_penalties_missed = user_profile['p13_penalties_missed']
    new_user.p13_goals_conceded = user_profile['p13_goals_conceded']
    new_user.p13_yellow_cards = user_profile['p13_yellow_cards']
    new_user.p13_red_cards = user_profile['p13_red_cards']
    new_user.p13_saves = user_profile['p13_saves']
    new_user.p13_bonus = user_profile['p13_bonus']
    new_user.p13_bps = user_profile['p13_bps']
    new_user.p13_team_jersey = user_profile['p13_team_jersey']
    new_user.p13_team_logo = user_profile['p13_team_logo']
    new_user.p13_team_colors = user_profile['p13_team_colors']
    new_user.p13_team_name = user_profile['p13_team_name']

    # player 14
    new_user.p14_chance_of_playing_next_round = user_profile['p14_chance_of_playing_next_round']
    new_user.p14_chance_of_playing_this_round = user_profile['p14_chance_of_playing_this_round']
    new_user.p14_cost_change_event = user_profile['p14_cost_change_event']
    new_user.p14_cost_change_event_fall = user_profile['p14_cost_change_event_fall']
    new_user.p14_cost_change_start = user_profile['p14_cost_change_start']
    new_user.p14_cost_change_start_fall = user_profile['p14_cost_change_start_fall']
    new_user.p14_dreamteam_count = user_profile['p14_dreamteam_count']
    new_user.p14_element_type = user_profile['p14_element_type']
    new_user.p14_event_points = user_profile['p14_event_points']
    new_user.p14_first_name = user_profile['p14_first_name']
    new_user.p14_form = user_profile['p14_form']
    new_user.p14_player_id = user_profile['p14_player_id']
    new_user.p14_in_dreamteam = user_profile['p14_in_dreamteam']
    new_user.p14_now_cost = user_profile['p14_now_cost']
    new_user.p14_photo = user_profile['p14_photo']
    new_user.p14_points_per_game = user_profile['p14_points_per_game']
    new_user.p14_second_name = user_profile['p14_second_name']
    new_user.p14_selected_by_percent = user_profile['p14_selected_by_percent']
    new_user.p14_special = user_profile['p14_special']
    new_user.p14_squad_number = user_profile['p14_squad_number']
    new_user.p14_status = user_profile['p14_status']
    new_user.p14_team = user_profile['p14_team']
    new_user.p14_team_code = user_profile['p14_team_code']
    new_user.p14_total_points = user_profile['p14_total_points']
    new_user.p14_value_form = user_profile['p14_value_form']
    new_user.p14_value_season = user_profile['p14_value_season']
    new_user.p14_web_name = user_profile['p14_web_name']
    new_user.p14_minutes = user_profile['p14_minutes']
    new_user.p14_goals_scored = user_profile['p14_goals_scored']
    new_user.p14_assists = user_profile['p14_assists']
    new_user.p14_clean_sheets = user_profile['p14_clean_sheets']
    new_user.p14_own_goals = user_profile['p14_own_goals']
    new_user.p14_penalties_saved = user_profile['p14_penalties_saved']
    new_user.p14_penalties_missed = user_profile['p14_penalties_missed']
    new_user.p14_goals_conceded = user_profile['p14_goals_conceded']
    new_user.p14_yellow_cards = user_profile['p14_yellow_cards']
    new_user.p14_red_cards = user_profile['p14_red_cards']
    new_user.p14_saves = user_profile['p14_saves']
    new_user.p14_bonus = user_profile['p14_bonus']
    new_user.p14_bps = user_profile['p14_bps']
    new_user.p14_team_jersey = user_profile['p14_team_jersey']
    new_user.p14_team_logo = user_profile['p14_team_logo']
    new_user.p14_team_colors = user_profile['p14_team_colors']
    new_user.p14_team_name = user_profile['p14_team_name']

    # player 15
    new_user.p15_chance_of_playing_next_round = user_profile['p15_chance_of_playing_next_round']
    new_user.p15_chance_of_playing_this_round = user_profile['p15_chance_of_playing_this_round']
    new_user.p15_cost_change_event = user_profile['p15_cost_change_event']
    new_user.p15_cost_change_event_fall = user_profile['p15_cost_change_event_fall']
    new_user.p15_cost_change_start = user_profile['p15_cost_change_start']
    new_user.p15_cost_change_start_fall = user_profile['p15_cost_change_start_fall']
    new_user.p15_dreamteam_count = user_profile['p15_dreamteam_count']
    new_user.p15_element_type = user_profile['p15_element_type']
    new_user.p15_event_points = user_profile['p15_event_points']
    new_user.p15_first_name = user_profile['p15_first_name']
    new_user.p15_form = user_profile['p15_form']
    new_user.p15_player_id = user_profile['p15_player_id']
    new_user.p15_in_dreamteam = user_profile['p15_in_dreamteam']
    new_user.p15_now_cost = user_profile['p15_now_cost']
    new_user.p15_photo = user_profile['p15_photo']
    new_user.p15_points_per_game = user_profile['p15_points_per_game']
    new_user.p15_second_name = user_profile['p15_second_name']
    new_user.p15_selected_by_percent = user_profile['p15_selected_by_percent']
    new_user.p15_special = user_profile['p15_special']
    new_user.p15_squad_number = user_profile['p15_squad_number']
    new_user.p15_status = user_profile['p15_status']
    new_user.p15_team = user_profile['p15_team']
    new_user.p15_team_code = user_profile['p15_team_code']
    new_user.p15_total_points = user_profile['p15_total_points']
    new_user.p15_value_form = user_profile['p15_value_form']
    new_user.p15_value_season = user_profile['p15_value_season']
    new_user.p15_web_name = user_profile['p15_web_name']
    new_user.p15_minutes = user_profile['p15_minutes']
    new_user.p15_goals_scored = user_profile['p15_goals_scored']
    new_user.p15_assists = user_profile['p15_assists']
    new_user.p15_clean_sheets = user_profile['p15_clean_sheets']
    new_user.p15_own_goals = user_profile['p15_own_goals']
    new_user.p15_penalties_saved = user_profile['p15_penalties_saved']
    new_user.p15_penalties_missed = user_profile['p15_penalties_missed']
    new_user.p15_goals_conceded = user_profile['p15_goals_conceded']
    new_user.p15_yellow_cards = user_profile['p15_yellow_cards']
    new_user.p15_red_cards = user_profile['p15_red_cards']
    new_user.p15_saves = user_profile['p15_saves']
    new_user.p15_bonus = user_profile['p15_bonus']
    new_user.p15_bps = user_profile['p15_bps']
    new_user.p15_team_jersey = user_profile['p15_team_jersey']
    new_user.p15_team_logo = user_profile['p15_team_logo']
    new_user.p15_team_colors = user_profile['p15_team_colors']
    new_user.p15_team_name = user_profile['p15_team_name']


    db.session.add(new_user)
    db.session.commit()
    # session['user_id'] = user_id
    flash(f'Welcome! {new_user.team_name}')
    return redirect(f'/user/{user_id}')


# LOGGING IN  ###################################################################
# login
@app.route('/logon', methods=['GET','POST'])
def login_user():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        temp = form.password.data
        user = Users.authenticate(email, password)

        # when logging build the user's profile
        create_profile(user.email, temp, user.team_id)

        # access the team dict imported from methods.py
        # we are interested if any transfers were made
        transfer_check = user_profile['transfers']['made']

        # if login is successful
        if user:
            session['user_id'] = user.id
            return redirect(f'/user/update/{user.id}')
        else:
            form.email.errors = ['Invalid username/password.']
    return render_template('login.html', form=form)


# update user's team table if no transfers were made
@app.route('/user/update/<int:user_id>', methods=["GET","POST"])
def update_user(user_id):
    team = Team.query.get_or_404(user_id)

    team.team_name = user_profile['team_name']
    team.fav_team = user_profile['fav_team']
    team.fav_team_id = user_profile['fav_team_id']
    team.fav_team_logo = user_profile['fav_team_logo']
    team.fav_team_colors = user_profile['fav_team_colors']
    team.fav_team_jersey = user_profile['fav_team_jersey']
    team.fav_team_jersey_goal = user_profile['fav_team_jersey_goal']
    team.classic_league_id = user_profile['classic_league_id']
    team.overall_points = user_profile['overall_points']
    team.gameweek_points = user_profile['gameweek_points']
    team.classic_league_name = user_profile['classic_league_name']
    team.classic_league_rank = user_profile['classic_league_rank']
    team.classic_league_rank_previous = user_profile['classic_league_rank_previous']

    # player 1
    team.p1_chance_of_playing_next_round = user_profile['p1_chance_of_playing_next_round']
    team.p1_chance_of_playing_this_round = user_profile['p1_chance_of_playing_this_round']
    team.p1_cost_change_event = user_profile['p1_cost_change_event']
    team.p1_cost_change_event_fall = user_profile['p1_cost_change_event_fall']
    team.p1_cost_change_start = user_profile['p1_cost_change_start']
    team.p1_cost_change_start_fall = user_profile['p1_cost_change_start_fall']
    team.p1_dreamteam_count = user_profile['p1_dreamteam_count']
    team.p1_element_type = user_profile['p1_element_type']
    team.p1_event_points = user_profile['p1_event_points']
    team.p1_first_name = user_profile['p1_first_name']
    team.p1_form = user_profile['p1_form']
    team.p1_player_id = user_profile['p1_player_id']
    team.p1_in_dreamteam = user_profile['p1_in_dreamteam']
    team.p1_now_cost = user_profile['p1_now_cost']
    team.p1_photo = user_profile['p1_photo']
    team.p1_points_per_game = user_profile['p1_points_per_game']
    team.p1_second_name = user_profile['p1_second_name']
    team.p1_selected_by_percent = user_profile['p1_selected_by_percent']
    team.p1_special = user_profile['p1_special']
    team.p1_squad_number = user_profile['p1_squad_number']
    team.p1_status = user_profile['p1_status']
    team.p1_team = user_profile['p1_team']
    team.p1_team_code = user_profile['p1_team_code']
    team.p1_total_points = user_profile['p1_total_points']
    team.p1_value_form = user_profile['p1_value_form']
    team.p1_value_season = user_profile['p1_value_season']
    team.p1_web_name = user_profile['p1_web_name']
    team.p1_minutes = user_profile['p1_minutes']
    team.p1_goals_scored = user_profile['p1_goals_scored']
    team.p1_assists = user_profile['p1_assists']
    team.p1_clean_sheets = user_profile['p1_clean_sheets']
    team.p1_own_goals = user_profile['p1_own_goals']
    team.p1_penalties_saved = user_profile['p1_penalties_saved']
    team.p1_penalties_missed = user_profile['p1_penalties_missed']
    team.p1_goals_conceded = user_profile['p1_goals_conceded']
    team.p1_yellow_cards = user_profile['p1_yellow_cards']
    team.p1_red_cards = user_profile['p1_red_cards']
    team.p1_saves = user_profile['p1_saves']
    team.p1_bonus = user_profile['p1_bonus']
    team.p1_bps = user_profile['p1_bps']
    team.p1_team_jersey = user_profile['p1_team_jersey']
    team.p1_team_logo = user_profile['p1_team_logo']
    team.p1_team_colors = user_profile['p1_team_colors']
    team.p1_team_name = user_profile['p1_team_name']

    # player 2
    team.p2_chance_of_playing_next_round = user_profile['p2_chance_of_playing_next_round']
    team.p2_chance_of_playing_this_round = user_profile['p2_chance_of_playing_this_round']
    team.p2_cost_change_event = user_profile['p2_cost_change_event']
    team.p2_cost_change_event_fall = user_profile['p2_cost_change_event_fall']
    team.p2_cost_change_start = user_profile['p2_cost_change_start']
    team.p2_cost_change_start_fall = user_profile['p2_cost_change_start_fall']
    team.p2_dreamteam_count = user_profile['p2_dreamteam_count']
    team.p2_element_type = user_profile['p2_element_type']
    team.p2_event_points = user_profile['p2_event_points']
    team.p2_first_name = user_profile['p2_first_name']
    team.p2_form = user_profile['p2_form']
    team.p2_player_id = user_profile['p2_player_id']
    team.p2_in_dreamteam = user_profile['p2_in_dreamteam']
    team.p2_now_cost = user_profile['p2_now_cost']
    team.p2_photo = user_profile['p2_photo']
    team.p2_points_per_game = user_profile['p2_points_per_game']
    team.p2_second_name = user_profile['p2_second_name']
    team.p2_selected_by_percent = user_profile['p2_selected_by_percent']
    team.p2_special = user_profile['p2_special']
    team.p2_squad_number = user_profile['p2_squad_number']
    team.p2_status = user_profile['p2_status']
    team.p2_team = user_profile['p2_team']
    team.p2_team_code = user_profile['p2_team_code']
    team.p2_total_points = user_profile['p2_total_points']
    team.p2_value_form = user_profile['p2_value_form']
    team.p2_value_season = user_profile['p2_value_season']
    team.p2_web_name = user_profile['p2_web_name']
    team.p2_minutes = user_profile['p2_minutes']
    team.p2_goals_scored = user_profile['p2_goals_scored']
    team.p2_assists = user_profile['p2_assists']
    team.p2_clean_sheets = user_profile['p2_clean_sheets']
    team.p2_own_goals = user_profile['p2_own_goals']
    team.p2_penalties_saved = user_profile['p2_penalties_saved']
    team.p2_penalties_missed = user_profile['p2_penalties_missed']
    team.p2_goals_conceded = user_profile['p2_goals_conceded']
    team.p2_yellow_cards = user_profile['p2_yellow_cards']
    team.p2_red_cards = user_profile['p2_red_cards']
    team.p2_saves = user_profile['p2_saves']
    team.p2_bonus = user_profile['p2_bonus']
    team.p2_bps = user_profile['p2_bps']
    team.p2_team_jersey = user_profile['p2_team_jersey']
    team.p2_team_logo = user_profile['p2_team_logo']
    team.p2_team_colors = user_profile['p2_team_colors']
    team.p2_team_name = user_profile['p2_team_name']

    # player 3
    team.p3_chance_of_playing_next_round = user_profile['p3_chance_of_playing_next_round']
    team.p3_chance_of_playing_this_round = user_profile['p3_chance_of_playing_this_round']
    team.p3_cost_change_event = user_profile['p3_cost_change_event']
    team.p3_cost_change_event_fall = user_profile['p3_cost_change_event_fall']
    team.p3_cost_change_start = user_profile['p3_cost_change_start']
    team.p3_cost_change_start_fall = user_profile['p3_cost_change_start_fall']
    team.p3_dreamteam_count = user_profile['p3_dreamteam_count']
    team.p3_element_type = user_profile['p3_element_type']
    team.p3_event_points = user_profile['p3_event_points']
    team.p3_first_name = user_profile['p3_first_name']
    team.p3_form = user_profile['p3_form']
    team.p3_player_id = user_profile['p3_player_id']
    team.p3_in_dreamteam = user_profile['p3_in_dreamteam']
    team.p3_now_cost = user_profile['p3_now_cost']
    team.p3_photo = user_profile['p3_photo']
    team.p3_points_per_game = user_profile['p3_points_per_game']
    team.p3_second_name = user_profile['p3_second_name']
    team.p3_selected_by_percent = user_profile['p3_selected_by_percent']
    team.p3_special = user_profile['p3_special']
    team.p3_squad_number = user_profile['p3_squad_number']
    team.p3_status = user_profile['p3_status']
    team.p3_team = user_profile['p3_team']
    team.p3_team_code = user_profile['p3_team_code']
    team.p3_total_points = user_profile['p3_total_points']
    team.p3_value_form = user_profile['p3_value_form']
    team.p3_value_season = user_profile['p3_value_season']
    team.p3_web_name = user_profile['p3_web_name']
    team.p3_minutes = user_profile['p3_minutes']
    team.p3_goals_scored = user_profile['p3_goals_scored']
    team.p3_assists = user_profile['p3_assists']
    team.p3_clean_sheets = user_profile['p3_clean_sheets']
    team.p3_own_goals = user_profile['p3_own_goals']
    team.p3_penalties_saved = user_profile['p3_penalties_saved']
    team.p3_penalties_missed = user_profile['p3_penalties_missed']
    team.p3_goals_conceded = user_profile['p3_goals_conceded']
    team.p3_yellow_cards = user_profile['p3_yellow_cards']
    team.p3_red_cards = user_profile['p3_red_cards']
    team.p3_saves = user_profile['p3_saves']
    team.p3_bonus = user_profile['p3_bonus']
    team.p3_bps = user_profile['p3_bps']
    team.p3_team_jersey = user_profile['p3_team_jersey']
    team.p3_team_logo = user_profile['p3_team_logo']
    team.p3_team_colors = user_profile['p3_team_colors']
    team.p3_team_name = user_profile['p3_team_name']

    # player 4
    team.p4_chance_of_playing_next_round = user_profile['p4_chance_of_playing_next_round']
    team.p4_chance_of_playing_this_round = user_profile['p4_chance_of_playing_this_round']
    team.p4_cost_change_event = user_profile['p4_cost_change_event']
    team.p4_cost_change_event_fall = user_profile['p4_cost_change_event_fall']
    team.p4_cost_change_start = user_profile['p4_cost_change_start']
    team.p4_cost_change_start_fall = user_profile['p4_cost_change_start_fall']
    team.p4_dreamteam_count = user_profile['p4_dreamteam_count']
    team.p4_element_type = user_profile['p4_element_type']
    team.p4_event_points = user_profile['p4_event_points']
    team.p4_first_name = user_profile['p4_first_name']
    team.p4_form = user_profile['p4_form']
    team.p4_player_id = user_profile['p4_player_id']
    team.p4_in_dreamteam = user_profile['p4_in_dreamteam']
    team.p4_now_cost = user_profile['p4_now_cost']
    team.p4_photo = user_profile['p4_photo']
    team.p4_points_per_game = user_profile['p4_points_per_game']
    team.p4_second_name = user_profile['p4_second_name']
    team.p4_selected_by_percent = user_profile['p4_selected_by_percent']
    team.p4_special = user_profile['p4_special']
    team.p4_squad_number = user_profile['p4_squad_number']
    team.p4_status = user_profile['p4_status']
    team.p4_team = user_profile['p4_team']
    team.p4_team_code = user_profile['p4_team_code']
    team.p4_total_points = user_profile['p4_total_points']
    team.p4_value_form = user_profile['p4_value_form']
    team.p4_value_season = user_profile['p4_value_season']
    team.p4_web_name = user_profile['p4_web_name']
    team.p4_minutes = user_profile['p4_minutes']
    team.p4_goals_scored = user_profile['p4_goals_scored']
    team.p4_assists = user_profile['p4_assists']
    team.p4_clean_sheets = user_profile['p4_clean_sheets']
    team.p4_own_goals = user_profile['p4_own_goals']
    team.p4_penalties_saved = user_profile['p4_penalties_saved']
    team.p4_penalties_missed = user_profile['p4_penalties_missed']
    team.p4_goals_conceded = user_profile['p4_goals_conceded']
    team.p4_yellow_cards = user_profile['p4_yellow_cards']
    team.p4_red_cards = user_profile['p4_red_cards']
    team.p4_saves = user_profile['p4_saves']
    team.p4_bonus = user_profile['p4_bonus']
    team.p4_bps = user_profile['p4_bps']
    team.p4_team_jersey = user_profile['p4_team_jersey']
    team.p4_team_logo = user_profile['p4_team_logo']
    team.p4_team_colors = user_profile['p4_team_colors']
    team.p4_team_name = user_profile['p4_team_name']

    # player 5
    team.p5_chance_of_playing_next_round = user_profile['p5_chance_of_playing_next_round']
    team.p5_chance_of_playing_this_round = user_profile['p5_chance_of_playing_this_round']
    team.p5_cost_change_event = user_profile['p5_cost_change_event']
    team.p5_cost_change_event_fall = user_profile['p5_cost_change_event_fall']
    team.p5_cost_change_start = user_profile['p5_cost_change_start']
    team.p5_cost_change_start_fall = user_profile['p5_cost_change_start_fall']
    team.p5_dreamteam_count = user_profile['p5_dreamteam_count']
    team.p5_element_type = user_profile['p5_element_type']
    team.p5_event_points = user_profile['p5_event_points']
    team.p5_first_name = user_profile['p5_first_name']
    team.p5_form = user_profile['p5_form']
    team.p5_player_id = user_profile['p5_player_id']
    team.p5_in_dreamteam = user_profile['p5_in_dreamteam']
    team.p5_now_cost = user_profile['p5_now_cost']
    team.p5_photo = user_profile['p5_photo']
    team.p5_points_per_game = user_profile['p5_points_per_game']
    team.p5_second_name = user_profile['p5_second_name']
    team.p5_selected_by_percent = user_profile['p5_selected_by_percent']
    team.p5_special = user_profile['p5_special']
    team.p5_squad_number = user_profile['p5_squad_number']
    team.p5_status = user_profile['p5_status']
    team.p5_team = user_profile['p5_team']
    team.p5_team_code = user_profile['p5_team_code']
    team.p5_total_points = user_profile['p5_total_points']
    team.p5_value_form = user_profile['p5_value_form']
    team.p5_value_season = user_profile['p5_value_season']
    team.p5_web_name = user_profile['p5_web_name']
    team.p5_minutes = user_profile['p5_minutes']
    team.p5_goals_scored = user_profile['p5_goals_scored']
    team.p5_assists = user_profile['p5_assists']
    team.p5_clean_sheets = user_profile['p5_clean_sheets']
    team.p5_own_goals = user_profile['p5_own_goals']
    team.p5_penalties_saved = user_profile['p5_penalties_saved']
    team.p5_penalties_missed = user_profile['p5_penalties_missed']
    team.p5_goals_conceded = user_profile['p5_goals_conceded']
    team.p5_yellow_cards = user_profile['p5_yellow_cards']
    team.p5_red_cards = user_profile['p5_red_cards']
    team.p5_saves = user_profile['p5_saves']
    team.p5_bonus = user_profile['p5_bonus']
    team.p5_bps = user_profile['p5_bps']
    team.p5_team_jersey = user_profile['p5_team_jersey']
    team.p5_team_logo = user_profile['p5_team_logo']
    team.p5_team_colors = user_profile['p5_team_colors']
    team.p5_team_name = user_profile['p5_team_name']

    # player 6
    team.p6_chance_of_playing_next_round = user_profile['p6_chance_of_playing_next_round']
    team.p6_chance_of_playing_this_round = user_profile['p6_chance_of_playing_this_round']
    team.p6_cost_change_event = user_profile['p6_cost_change_event']
    team.p6_cost_change_event_fall = user_profile['p6_cost_change_event_fall']
    team.p6_cost_change_start = user_profile['p6_cost_change_start']
    team.p6_cost_change_start_fall = user_profile['p6_cost_change_start_fall']
    team.p6_dreamteam_count = user_profile['p6_dreamteam_count']
    team.p6_element_type = user_profile['p6_element_type']
    team.p6_event_points = user_profile['p6_event_points']
    team.p6_first_name = user_profile['p6_first_name']
    team.p6_form = user_profile['p6_form']
    team.p6_player_id = user_profile['p6_player_id']
    team.p6_in_dreamteam = user_profile['p6_in_dreamteam']
    team.p6_now_cost = user_profile['p6_now_cost']
    team.p6_photo = user_profile['p6_photo']
    team.p6_points_per_game = user_profile['p6_points_per_game']
    team.p6_second_name = user_profile['p6_second_name']
    team.p6_selected_by_percent = user_profile['p6_selected_by_percent']
    team.p6_special = user_profile['p6_special']
    team.p6_squad_number = user_profile['p6_squad_number']
    team.p6_status = user_profile['p6_status']
    team.p6_team = user_profile['p6_team']
    team.p6_team_code = user_profile['p6_team_code']
    team.p6_total_points = user_profile['p6_total_points']
    team.p6_value_form = user_profile['p6_value_form']
    team.p6_value_season = user_profile['p6_value_season']
    team.p6_web_name = user_profile['p6_web_name']
    team.p6_minutes = user_profile['p6_minutes']
    team.p6_goals_scored = user_profile['p6_goals_scored']
    team.p6_assists = user_profile['p6_assists']
    team.p6_clean_sheets = user_profile['p6_clean_sheets']
    team.p6_own_goals = user_profile['p6_own_goals']
    team.p6_penalties_saved = user_profile['p6_penalties_saved']
    team.p6_penalties_missed = user_profile['p6_penalties_missed']
    team.p6_goals_conceded = user_profile['p6_goals_conceded']
    team.p6_yellow_cards = user_profile['p6_yellow_cards']
    team.p6_red_cards = user_profile['p6_red_cards']
    team.p6_saves = user_profile['p6_saves']
    team.p6_bonus = user_profile['p6_bonus']
    team.p6_bps = user_profile['p6_bps']
    team.p6_team_jersey = user_profile['p6_team_jersey']
    team.p6_team_logo = user_profile['p6_team_logo']
    team.p6_team_colors = user_profile['p6_team_colors']
    team.p6_team_name = user_profile['p6_team_name']

    # player 7
    team.p7_chance_of_playing_next_round = user_profile['p7_chance_of_playing_next_round']
    team.p7_chance_of_playing_this_round = user_profile['p7_chance_of_playing_this_round']
    team.p7_cost_change_event = user_profile['p7_cost_change_event']
    team.p7_cost_change_event_fall = user_profile['p7_cost_change_event_fall']
    team.p7_cost_change_start = user_profile['p7_cost_change_start']
    team.p7_cost_change_start_fall = user_profile['p7_cost_change_start_fall']
    team.p7_dreamteam_count = user_profile['p7_dreamteam_count']
    team.p7_element_type = user_profile['p7_element_type']
    team.p7_event_points = user_profile['p7_event_points']
    team.p7_first_name = user_profile['p7_first_name']
    team.p7_form = user_profile['p7_form']
    team.p7_player_id = user_profile['p7_player_id']
    team.p7_in_dreamteam = user_profile['p7_in_dreamteam']
    team.p7_now_cost = user_profile['p7_now_cost']
    team.p7_photo = user_profile['p7_photo']
    team.p7_points_per_game = user_profile['p7_points_per_game']
    team.p7_second_name = user_profile['p7_second_name']
    team.p7_selected_by_percent = user_profile['p7_selected_by_percent']
    team.p7_special = user_profile['p7_special']
    team.p7_squad_number = user_profile['p7_squad_number']
    team.p7_status = user_profile['p7_status']
    team.p7_team = user_profile['p7_team']
    team.p7_team_code = user_profile['p7_team_code']
    team.p7_total_points = user_profile['p7_total_points']
    team.p7_value_form = user_profile['p7_value_form']
    team.p7_value_season = user_profile['p7_value_season']
    team.p7_web_name = user_profile['p7_web_name']
    team.p7_minutes = user_profile['p7_minutes']
    team.p7_goals_scored = user_profile['p7_goals_scored']
    team.p7_assists = user_profile['p7_assists']
    team.p7_clean_sheets = user_profile['p7_clean_sheets']
    team.p7_own_goals = user_profile['p7_own_goals']
    team.p7_penalties_saved = user_profile['p7_penalties_saved']
    team.p7_penalties_missed = user_profile['p7_penalties_missed']
    team.p7_goals_conceded = user_profile['p7_goals_conceded']
    team.p7_yellow_cards = user_profile['p7_yellow_cards']
    team.p7_red_cards = user_profile['p7_red_cards']
    team.p7_saves = user_profile['p7_saves']
    team.p7_bonus = user_profile['p7_bonus']
    team.p7_bps = user_profile['p7_bps']
    team.p7_team_jersey = user_profile['p7_team_jersey']
    team.p7_team_logo = user_profile['p7_team_logo']
    team.p7_team_colors = user_profile['p7_team_colors']
    team.p7_team_name = user_profile['p7_team_name']

    # player 8
    team.p8_chance_of_playing_next_round = user_profile['p8_chance_of_playing_next_round']
    team.p8_chance_of_playing_this_round = user_profile['p8_chance_of_playing_this_round']
    team.p8_cost_change_event = user_profile['p8_cost_change_event']
    team.p8_cost_change_event_fall = user_profile['p8_cost_change_event_fall']
    team.p8_cost_change_start = user_profile['p8_cost_change_start']
    team.p8_cost_change_start_fall = user_profile['p8_cost_change_start_fall']
    team.p8_dreamteam_count = user_profile['p8_dreamteam_count']
    team.p8_element_type = user_profile['p8_element_type']
    team.p8_event_points = user_profile['p8_event_points']
    team.p8_first_name = user_profile['p8_first_name']
    team.p8_form = user_profile['p8_form']
    team.p8_player_id = user_profile['p8_player_id']
    team.p8_in_dreamteam = user_profile['p8_in_dreamteam']
    team.p8_now_cost = user_profile['p8_now_cost']
    team.p8_photo = user_profile['p8_photo']
    team.p8_points_per_game = user_profile['p8_points_per_game']
    team.p8_second_name = user_profile['p8_second_name']
    team.p8_selected_by_percent = user_profile['p8_selected_by_percent']
    team.p8_special = user_profile['p8_special']
    team.p8_squad_number = user_profile['p8_squad_number']
    team.p8_status = user_profile['p8_status']
    team.p8_team = user_profile['p8_team']
    team.p8_team_code = user_profile['p8_team_code']
    team.p8_total_points = user_profile['p8_total_points']
    team.p8_value_form = user_profile['p8_value_form']
    team.p8_value_season = user_profile['p8_value_season']
    team.p8_web_name = user_profile['p8_web_name']
    team.p8_minutes = user_profile['p8_minutes']
    team.p8_goals_scored = user_profile['p8_goals_scored']
    team.p8_assists = user_profile['p8_assists']
    team.p8_clean_sheets = user_profile['p8_clean_sheets']
    team.p8_own_goals = user_profile['p8_own_goals']
    team.p8_penalties_saved = user_profile['p8_penalties_saved']
    team.p8_penalties_missed = user_profile['p8_penalties_missed']
    team.p8_goals_conceded = user_profile['p8_goals_conceded']
    team.p8_yellow_cards = user_profile['p8_yellow_cards']
    team.p8_red_cards = user_profile['p8_red_cards']
    team.p8_saves = user_profile['p8_saves']
    team.p8_bonus = user_profile['p8_bonus']
    team.p8_bps = user_profile['p8_bps']
    team.p8_team_jersey = user_profile['p8_team_jersey']
    team.p8_team_logo = user_profile['p8_team_logo']
    team.p8_team_colors = user_profile['p8_team_colors']
    team.p8_team_name = user_profile['p8_team_name']

    # player 9
    team.p9_chance_of_playing_next_round = user_profile['p9_chance_of_playing_next_round']
    team.p9_chance_of_playing_this_round = user_profile['p9_chance_of_playing_this_round']
    team.p9_cost_change_event = user_profile['p9_cost_change_event']
    team.p9_cost_change_event_fall = user_profile['p9_cost_change_event_fall']
    team.p9_cost_change_start = user_profile['p9_cost_change_start']
    team.p9_cost_change_start_fall = user_profile['p9_cost_change_start_fall']
    team.p9_dreamteam_count = user_profile['p9_dreamteam_count']
    team.p9_element_type = user_profile['p9_element_type']
    team.p9_event_points = user_profile['p9_event_points']
    team.p9_first_name = user_profile['p9_first_name']
    team.p9_form = user_profile['p9_form']
    team.p9_player_id = user_profile['p9_player_id']
    team.p9_in_dreamteam = user_profile['p9_in_dreamteam']
    team.p9_now_cost = user_profile['p9_now_cost']
    team.p9_photo = user_profile['p9_photo']
    team.p9_points_per_game = user_profile['p9_points_per_game']
    team.p9_second_name = user_profile['p9_second_name']
    team.p9_selected_by_percent = user_profile['p9_selected_by_percent']
    team.p9_special = user_profile['p9_special']
    team.p9_squad_number = user_profile['p9_squad_number']
    team.p9_status = user_profile['p9_status']
    team.p9_team = user_profile['p9_team']
    team.p9_team_code = user_profile['p9_team_code']
    team.p9_total_points = user_profile['p9_total_points']
    team.p9_value_form = user_profile['p9_value_form']
    team.p9_value_season = user_profile['p9_value_season']
    team.p9_web_name = user_profile['p9_web_name']
    team.p9_minutes = user_profile['p9_minutes']
    team.p9_goals_scored = user_profile['p9_goals_scored']
    team.p9_assists = user_profile['p9_assists']
    team.p9_clean_sheets = user_profile['p9_clean_sheets']
    team.p9_own_goals = user_profile['p9_own_goals']
    team.p9_penalties_saved = user_profile['p9_penalties_saved']
    team.p9_penalties_missed = user_profile['p9_penalties_missed']
    team.p9_goals_conceded = user_profile['p9_goals_conceded']
    team.p9_yellow_cards = user_profile['p9_yellow_cards']
    team.p9_red_cards = user_profile['p9_red_cards']
    team.p9_saves = user_profile['p9_saves']
    team.p9_bonus = user_profile['p9_bonus']
    team.p9_bps = user_profile['p9_bps']
    team.p9_team_jersey = user_profile['p9_team_jersey']
    team.p9_team_logo = user_profile['p9_team_logo']
    team.p9_team_colors = user_profile['p9_team_colors']
    team.p9_team_name = user_profile['p9_team_name']

    # player 10
    team.p10_chance_of_playing_next_round = user_profile['p10_chance_of_playing_next_round']
    team.p10_chance_of_playing_this_round = user_profile['p10_chance_of_playing_this_round']
    team.p10_cost_change_event = user_profile['p10_cost_change_event']
    team.p10_cost_change_event_fall = user_profile['p10_cost_change_event_fall']
    team.p10_cost_change_start = user_profile['p10_cost_change_start']
    team.p10_cost_change_start_fall = user_profile['p10_cost_change_start_fall']
    team.p10_dreamteam_count = user_profile['p10_dreamteam_count']
    team.p10_element_type = user_profile['p10_element_type']
    team.p10_event_points = user_profile['p10_event_points']
    team.p10_first_name = user_profile['p10_first_name']
    team.p10_form = user_profile['p10_form']
    team.p10_player_id = user_profile['p10_player_id']
    team.p10_in_dreamteam = user_profile['p10_in_dreamteam']
    team.p10_now_cost = user_profile['p10_now_cost']
    team.p10_photo = user_profile['p10_photo']
    team.p10_points_per_game = user_profile['p10_points_per_game']
    team.p10_second_name = user_profile['p10_second_name']
    team.p10_selected_by_percent = user_profile['p10_selected_by_percent']
    team.p10_special = user_profile['p10_special']
    team.p10_squad_number = user_profile['p10_squad_number']
    team.p10_status = user_profile['p10_status']
    team.p10_team = user_profile['p10_team']
    team.p10_team_code = user_profile['p10_team_code']
    team.p10_total_points = user_profile['p10_total_points']
    team.p10_value_form = user_profile['p10_value_form']
    team.p10_value_season = user_profile['p10_value_season']
    team.p10_web_name = user_profile['p10_web_name']
    team.p10_minutes = user_profile['p10_minutes']
    team.p10_goals_scored = user_profile['p10_goals_scored']
    team.p10_assists = user_profile['p10_assists']
    team.p10_clean_sheets = user_profile['p10_clean_sheets']
    team.p10_own_goals = user_profile['p10_own_goals']
    team.p10_penalties_saved = user_profile['p10_penalties_saved']
    team.p10_penalties_missed = user_profile['p10_penalties_missed']
    team.p10_goals_conceded = user_profile['p10_goals_conceded']
    team.p10_yellow_cards = user_profile['p10_yellow_cards']
    team.p10_red_cards = user_profile['p10_red_cards']
    team.p10_saves = user_profile['p10_saves']
    team.p10_bonus = user_profile['p10_bonus']
    team.p10_bps = user_profile['p10_bps']
    team.p10_team_jersey = user_profile['p10_team_jersey']
    team.p10_team_logo = user_profile['p10_team_logo']
    team.p10_team_colors = user_profile['p10_team_colors']
    team.p10_team_name = user_profile['p10_team_name']

    # player 11
    team.p11_chance_of_playing_next_round = user_profile['p11_chance_of_playing_next_round']
    team.p11_chance_of_playing_this_round = user_profile['p11_chance_of_playing_this_round']
    team.p11_cost_change_event = user_profile['p11_cost_change_event']
    team.p11_cost_change_event_fall = user_profile['p11_cost_change_event_fall']
    team.p11_cost_change_start = user_profile['p11_cost_change_start']
    team.p11_cost_change_start_fall = user_profile['p11_cost_change_start_fall']
    team.p11_dreamteam_count = user_profile['p11_dreamteam_count']
    team.p11_element_type = user_profile['p11_element_type']
    team.p11_event_points = user_profile['p11_event_points']
    team.p11_first_name = user_profile['p11_first_name']
    team.p11_form = user_profile['p11_form']
    team.p11_player_id = user_profile['p11_player_id']
    team.p11_in_dreamteam = user_profile['p11_in_dreamteam']
    team.p11_now_cost = user_profile['p11_now_cost']
    team.p11_photo = user_profile['p11_photo']
    team.p11_points_per_game = user_profile['p11_points_per_game']
    team.p11_second_name = user_profile['p11_second_name']
    team.p11_selected_by_percent = user_profile['p11_selected_by_percent']
    team.p11_special = user_profile['p11_special']
    team.p11_squad_number = user_profile['p11_squad_number']
    team.p11_status = user_profile['p11_status']
    team.p11_team = user_profile['p11_team']
    team.p11_team_code = user_profile['p11_team_code']
    team.p11_total_points = user_profile['p11_total_points']
    team.p11_value_form = user_profile['p11_value_form']
    team.p11_value_season = user_profile['p11_value_season']
    team.p11_web_name = user_profile['p11_web_name']
    team.p11_minutes = user_profile['p11_minutes']
    team.p11_goals_scored = user_profile['p11_goals_scored']
    team.p11_assists = user_profile['p11_assists']
    team.p11_clean_sheets = user_profile['p11_clean_sheets']
    team.p11_own_goals = user_profile['p11_own_goals']
    team.p11_penalties_saved = user_profile['p11_penalties_saved']
    team.p11_penalties_missed = user_profile['p11_penalties_missed']
    team.p11_goals_conceded = user_profile['p11_goals_conceded']
    team.p11_yellow_cards = user_profile['p11_yellow_cards']
    team.p11_red_cards = user_profile['p11_red_cards']
    team.p11_saves = user_profile['p11_saves']
    team.p11_bonus = user_profile['p11_bonus']
    team.p11_bps = user_profile['p11_bps']
    team.p11_team_jersey = user_profile['p11_team_jersey']
    team.p11_team_logo = user_profile['p11_team_logo']
    team.p11_team_colors = user_profile['p11_team_colors']
    team.p11_team_name = user_profile['p11_team_name']

    # player 12
    team.p12_chance_of_playing_next_round = user_profile['p12_chance_of_playing_next_round']
    team.p12_chance_of_playing_this_round = user_profile['p12_chance_of_playing_this_round']
    team.p12_cost_change_event = user_profile['p12_cost_change_event']
    team.p12_cost_change_event_fall = user_profile['p12_cost_change_event_fall']
    team.p12_cost_change_start = user_profile['p12_cost_change_start']
    team.p12_cost_change_start_fall = user_profile['p12_cost_change_start_fall']
    team.p12_dreamteam_count = user_profile['p12_dreamteam_count']
    team.p12_element_type = user_profile['p12_element_type']
    team.p12_event_points = user_profile['p12_event_points']
    team.p12_first_name = user_profile['p12_first_name']
    team.p12_form = user_profile['p12_form']
    team.p12_player_id = user_profile['p12_player_id']
    team.p12_in_dreamteam = user_profile['p12_in_dreamteam']
    team.p12_now_cost = user_profile['p12_now_cost']
    team.p12_photo = user_profile['p12_photo']
    team.p12_points_per_game = user_profile['p12_points_per_game']
    team.p12_second_name = user_profile['p12_second_name']
    team.p12_selected_by_percent = user_profile['p12_selected_by_percent']
    team.p12_special = user_profile['p12_special']
    team.p12_squad_number = user_profile['p12_squad_number']
    team.p12_status = user_profile['p12_status']
    team.p12_team = user_profile['p12_team']
    team.p12_team_code = user_profile['p12_team_code']
    team.p12_total_points = user_profile['p12_total_points']
    team.p12_value_form = user_profile['p12_value_form']
    team.p12_value_season = user_profile['p12_value_season']
    team.p12_web_name = user_profile['p12_web_name']
    team.p12_minutes = user_profile['p12_minutes']
    team.p12_goals_scored = user_profile['p12_goals_scored']
    team.p12_assists = user_profile['p12_assists']
    team.p12_clean_sheets = user_profile['p12_clean_sheets']
    team.p12_own_goals = user_profile['p12_own_goals']
    team.p12_penalties_saved = user_profile['p12_penalties_saved']
    team.p12_penalties_missed = user_profile['p12_penalties_missed']
    team.p12_goals_conceded = user_profile['p12_goals_conceded']
    team.p12_yellow_cards = user_profile['p12_yellow_cards']
    team.p12_red_cards = user_profile['p12_red_cards']
    team.p12_saves = user_profile['p12_saves']
    team.p12_bonus = user_profile['p12_bonus']
    team.p12_bps = user_profile['p12_bps']
    team.p12_team_jersey = user_profile['p12_team_jersey']
    team.p12_team_logo = user_profile['p12_team_logo']
    team.p12_team_colors = user_profile['p12_team_colors']
    team.p12_team_name = user_profile['p12_team_name']

    # player 13
    team.p13_chance_of_playing_next_round = user_profile['p13_chance_of_playing_next_round']
    team.p13_chance_of_playing_this_round = user_profile['p13_chance_of_playing_this_round']
    team.p13_cost_change_event = user_profile['p13_cost_change_event']
    team.p13_cost_change_event_fall = user_profile['p13_cost_change_event_fall']
    team.p13_cost_change_start = user_profile['p13_cost_change_start']
    team.p13_cost_change_start_fall = user_profile['p13_cost_change_start_fall']
    team.p13_dreamteam_count = user_profile['p13_dreamteam_count']
    team.p13_element_type = user_profile['p13_element_type']
    team.p13_event_points = user_profile['p13_event_points']
    team.p13_first_name = user_profile['p13_first_name']
    team.p13_form = user_profile['p13_form']
    team.p13_player_id = user_profile['p13_player_id']
    team.p13_in_dreamteam = user_profile['p13_in_dreamteam']
    team.p13_now_cost = user_profile['p13_now_cost']
    team.p13_photo = user_profile['p13_photo']
    team.p13_points_per_game = user_profile['p13_points_per_game']
    team.p13_second_name = user_profile['p13_second_name']
    team.p13_selected_by_percent = user_profile['p13_selected_by_percent']
    team.p13_special = user_profile['p13_special']
    team.p13_squad_number = user_profile['p13_squad_number']
    team.p13_status = user_profile['p13_status']
    team.p13_team = user_profile['p13_team']
    team.p13_team_code = user_profile['p13_team_code']
    team.p13_total_points = user_profile['p13_total_points']
    team.p13_value_form = user_profile['p13_value_form']
    team.p13_value_season = user_profile['p13_value_season']
    team.p13_web_name = user_profile['p13_web_name']
    team.p13_minutes = user_profile['p13_minutes']
    team.p13_goals_scored = user_profile['p13_goals_scored']
    team.p13_assists = user_profile['p13_assists']
    team.p13_clean_sheets = user_profile['p13_clean_sheets']
    team.p13_own_goals = user_profile['p13_own_goals']
    team.p13_penalties_saved = user_profile['p13_penalties_saved']
    team.p13_penalties_missed = user_profile['p13_penalties_missed']
    team.p13_goals_conceded = user_profile['p13_goals_conceded']
    team.p13_yellow_cards = user_profile['p13_yellow_cards']
    team.p13_red_cards = user_profile['p13_red_cards']
    team.p13_saves = user_profile['p13_saves']
    team.p13_bonus = user_profile['p13_bonus']
    team.p13_bps = user_profile['p13_bps']
    team.p13_team_jersey = user_profile['p13_team_jersey']
    team.p13_team_logo = user_profile['p13_team_logo']
    team.p13_team_colors = user_profile['p13_team_colors']
    team.p13_team_name = user_profile['p13_team_name']

    # player 14
    team.p14_chance_of_playing_next_round = user_profile['p14_chance_of_playing_next_round']
    team.p14_chance_of_playing_this_round = user_profile['p14_chance_of_playing_this_round']
    team.p14_cost_change_event = user_profile['p14_cost_change_event']
    team.p14_cost_change_event_fall = user_profile['p14_cost_change_event_fall']
    team.p14_cost_change_start = user_profile['p14_cost_change_start']
    team.p14_cost_change_start_fall = user_profile['p14_cost_change_start_fall']
    team.p14_dreamteam_count = user_profile['p14_dreamteam_count']
    team.p14_element_type = user_profile['p14_element_type']
    team.p14_event_points = user_profile['p14_event_points']
    team.p14_first_name = user_profile['p14_first_name']
    team.p14_form = user_profile['p14_form']
    team.p14_player_id = user_profile['p14_player_id']
    team.p14_in_dreamteam = user_profile['p14_in_dreamteam']
    team.p14_now_cost = user_profile['p14_now_cost']
    team.p14_photo = user_profile['p14_photo']
    team.p14_points_per_game = user_profile['p14_points_per_game']
    team.p14_second_name = user_profile['p14_second_name']
    team.p14_selected_by_percent = user_profile['p14_selected_by_percent']
    team.p14_special = user_profile['p14_special']
    team.p14_squad_number = user_profile['p14_squad_number']
    team.p14_status = user_profile['p14_status']
    team.p14_team = user_profile['p14_team']
    team.p14_team_code = user_profile['p14_team_code']
    team.p14_total_points = user_profile['p14_total_points']
    team.p14_value_form = user_profile['p14_value_form']
    team.p14_value_season = user_profile['p14_value_season']
    team.p14_web_name = user_profile['p14_web_name']
    team.p14_minutes = user_profile['p14_minutes']
    team.p14_goals_scored = user_profile['p14_goals_scored']
    team.p14_assists = user_profile['p14_assists']
    team.p14_clean_sheets = user_profile['p14_clean_sheets']
    team.p14_own_goals = user_profile['p14_own_goals']
    team.p14_penalties_saved = user_profile['p14_penalties_saved']
    team.p14_penalties_missed = user_profile['p14_penalties_missed']
    team.p14_goals_conceded = user_profile['p14_goals_conceded']
    team.p14_yellow_cards = user_profile['p14_yellow_cards']
    team.p14_red_cards = user_profile['p14_red_cards']
    team.p14_saves = user_profile['p14_saves']
    team.p14_bonus = user_profile['p14_bonus']
    team.p14_bps = user_profile['p14_bps']
    team.p14_team_jersey = user_profile['p14_team_jersey']
    team.p14_team_logo = user_profile['p14_team_logo']
    team.p14_team_colors = user_profile['p14_team_colors']
    team.p14_team_name = user_profile['p14_team_name']

    # player 15
    team.p15_chance_of_playing_next_round = user_profile['p15_chance_of_playing_next_round']
    team.p15_chance_of_playing_this_round = user_profile['p15_chance_of_playing_this_round']
    team.p15_cost_change_event = user_profile['p15_cost_change_event']
    team.p15_cost_change_event_fall = user_profile['p15_cost_change_event_fall']
    team.p15_cost_change_start = user_profile['p15_cost_change_start']
    team.p15_cost_change_start_fall = user_profile['p15_cost_change_start_fall']
    team.p15_dreamteam_count = user_profile['p15_dreamteam_count']
    team.p15_element_type = user_profile['p15_element_type']
    team.p15_event_points = user_profile['p15_event_points']
    team.p15_first_name = user_profile['p15_first_name']
    team.p15_form = user_profile['p15_form']
    team.p15_player_id = user_profile['p15_player_id']
    team.p15_in_dreamteam = user_profile['p15_in_dreamteam']
    team.p15_now_cost = user_profile['p15_now_cost']
    team.p15_photo = user_profile['p15_photo']
    team.p15_points_per_game = user_profile['p15_points_per_game']
    team.p15_second_name = user_profile['p15_second_name']
    team.p15_selected_by_percent = user_profile['p15_selected_by_percent']
    team.p15_special = user_profile['p15_special']
    team.p15_squad_number = user_profile['p15_squad_number']
    team.p15_status = user_profile['p15_status']
    team.p15_team = user_profile['p15_team']
    team.p15_team_code = user_profile['p15_team_code']
    team.p15_total_points = user_profile['p15_total_points']
    team.p15_value_form = user_profile['p15_value_form']
    team.p15_value_season = user_profile['p15_value_season']
    team.p15_web_name = user_profile['p15_web_name']
    team.p15_minutes = user_profile['p15_minutes']
    team.p15_goals_scored = user_profile['p15_goals_scored']
    team.p15_assists = user_profile['p15_assists']
    team.p15_clean_sheets = user_profile['p15_clean_sheets']
    team.p15_own_goals = user_profile['p15_own_goals']
    team.p15_penalties_saved = user_profile['p15_penalties_saved']
    team.p15_penalties_missed = user_profile['p15_penalties_missed']
    team.p15_goals_conceded = user_profile['p15_goals_conceded']
    team.p15_yellow_cards = user_profile['p15_yellow_cards']
    team.p15_red_cards = user_profile['p15_red_cards']
    team.p15_saves = user_profile['p15_saves']
    team.p15_bonus = user_profile['p15_bonus']
    team.p15_bps = user_profile['p15_bps']
    team.p15_team_jersey = user_profile['p15_team_jersey']
    team.p15_team_logo = user_profile['p15_team_logo']
    team.p15_team_colors = user_profile['p15_team_colors']
    team.p15_team_name = user_profile['p15_team_name']


    db.session.commit()
    session['user_id'] = user_id
    flash('Team Updated!')
    return redirect(f'/user/{user_id}')
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        temp = form.password.data
        user = Users.authenticate(email, password)

        # when logging build the user's profile
        #create_profile(user.email, temp, user.team_id)

        # access the team dict imported from methods.py
        # we are interested if any transfers were made
        #transfer_check = user_profile['transfers']['made']

        # if login is successful
        if user:
            session['user_id'] = user.id
            return redirect(f'/user/{user.id}')
        else:
            form.email.errors = ['Invalid username/password.']
    return render_template('login.html', form=form)


# USER ROUTES ####################################################################
# USER's route
@app.route('/user/<int:user_id>')
def user_route(user_id):
    user = Users.query.get_or_404(user_id)
    team = Team.query.get_or_404(user_id)
    return render_template('user.html', user=user, team=team)


# TEAM ROSTER route
@app.route('/user/roster/<int:user_id>/<int:sort_num>')
def user_roster(user_id, sort_num):
    player = Team.query.get_or_404(user_id)
    if sort_num == 1:
        roster = organize_by_total_points()
    if sort_num == 2:
        roster = organize_by_event_points()
    if sort_num == 3:
        roster = organize_by_points_per_game()
    if sort_num == 4:
        roster = organize_by_form()
    if sort_num == 5:
        roster = organize_by_minutes()
    if sort_num == 6:
        roster = organize_by_price()
    if sort_num == 7:
        roster = organize_by_position()
    return render_template('users_players.html', player=player, user_profile=user_profile, roster=roster, sort_num=sort_num)


# TEAM ANALYSIS route
@app.route('/analysis')
def team_analysise_route():
    return render_template('home.html')


# LEAGUE TABLES route
@app.route('/user/league_tables/<int:user_id>')
def league_tables_route(user_id):
    user = Users.query.get_or_404(user_id)
    player = Team.query.get_or_404(user_id)
    return render_template('league_tables.html', user=user, player=player, team=team)


# AWARDS route
@app.route('/user/awards/<int:user_id>')
def awards_route(user_id):
    user = Users.query.get_or_404(user_id)
    player = Team.query.get_or_404(user_id)
    return render_template('awards.html', user=user, player=player)


# TEAM HISTORY route
@app.route('/team_history')
def team_history_route():
    return render_template('home.html')


# CHAT route
@app.route('/chat/<int:user_id>')
def chat_route(user_id):
    player = Team.query.get_or_404(user_id)
    return render_template('chat.html', player=player, team=team)


# LOGGING OUT ##################################################################
# logout
@app.route('/logout')
def logout():
    session.pop('user_id')
    user_profile['roster'] = []
    team = []
    return redirect('/')
